In [2]:
import pandas as pd
import numpy as np
import sklearn
import scipy
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pip install lightgbm

Requirement already satisfied: lightgbm in /opt/anaconda3/lib/python3.13/site-packages (4.7.0)
Requirement already satisfied: narwhals>=1.15 in /opt/anaconda3/lib/python3.13/site-packages (from lightgbm) (2.7.0)
Requirement already satisfied: numpy>=1.21.3 in /opt/anaconda3/lib/python3.13/site-packages (from lightgbm) (2.3.5)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from lightgbm) (1.16.3)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import lightgbm as lgb

In [5]:
df_train = pd.read_csv("../data/df_no_outliers.csv")
df_test = pd.read_csv("../data/df_test_no_outliers.csv")

**Results table**


Create two empty Pandas DataFrames with columns 'model', 'train', 'test'. Let's call the first one result_MAE and the second one result_RMSE. We will fill these tables with the results of the models.

In [7]:
result_MAE = pd.DataFrame(columns = ['model','train','test'])
result_RMSE = pd.DataFrame(columns = ['model','train','test'])


**Linear Regression**

Initialize linear regression from sklearn with no parameters.

Fit your model and make predictions on training and test features. Save it as new columns in data.

Compute MAE (Mean Absolute Error) on training and test targets.

Calculate RMSE (Root Mean Square Error) on training and test objectives.

Insert your metrics into tables result_MAE and result_RMSE with model name 'linear_regression'.

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

In [11]:
x_train = df_train[["bathrooms", "bedrooms"]]
y_train = df_train["price"]

x_test = df_test[['bathrooms','bedrooms']]
y_test = df_test['price']

In [12]:
linear_regression = LinearRegression()
linear_regression.fit(x_train, y_train)

LinearRegression()

In [52]:
y_pred_train_lr = linear_regression.predict(x_train)
y_pred_test_lr = linear_regression.predict(x_test)

In [53]:
mae_train_lr = mean_absolute_error(y_train, y_pred_train)
mae_test_lr = mean_absolute_error(y_test, y_pred_test)

In [54]:
mae_train_lr

781.5504727213308

In [55]:
mae_test_lr

786.3839818421121

In [57]:
rmse_train_lr = root_mean_squared_error(y_train, y_pred_train)
rmse_test_lr = root_mean_squared_error(y_test, y_pred_test)

In [58]:
rmse_train_lr

1115.809281258837

In [59]:
rmse_test_lr

1354.450529740186

In [46]:
result_MAE.loc[0] = ['linear_regression', mae_train_lr, mae_test_lr]
result_RMSE.loc[0] = ['linear_regression', rmse_train_lr, rmse_test_lr]

**Decision Tree**

Initialize decision tree regressor from sklearn with fixed random_state=21.
    
Fit it to train features and train target and make prediction on train and test features. Save it as a new column in data.
    
Compute MAE (Mean Absolute Error) on train and test targets.
    
Compute RMSE (Root Mean Square Error) on train and test targets.
    
Insert your metrics into tables result_MAE and result_RMSE with model name 'decision_tree'.

In [48]:
from sklearn.tree import DecisionTreeRegressor

In [49]:
tree = DecisionTreeRegressor(random_state=21)

In [50]:
tree.fit(x_train, y_train)

DecisionTreeRegressor(random_state=21)

In [51]:
y_pred_train_dt = tree.predict(x_train)
y_pred_test_dt = tree.predict(x_test)

In [60]:
mae_train_dt = mean_absolute_error(y_train, y_pred_train_dt)
mae_test_dt = mean_absolute_error(y_test, y_pred_test_dt)

In [61]:
rmse_train_dt = root_mean_squared_error(y_train, y_pred_train_dt)
rmse_test_dt = root_mean_squared_error(y_test, y_pred_test_dt)

In [65]:
result_MAE.loc[1] = ['decision_tree', mae_train_dt, mae_test_dt]
result_RMSE.loc[1] = ['decision_tree', rmse_train_dt, rmse_test_dt]

In [66]:
result_MAE

               model       train        test
0  linear_regression  781.550473  786.383982
1      decision_tree  753.675997  756.114142

In [67]:
result_RMSE

               model        train         test
0  linear_regression  1115.809281  1354.450530
1      decision_tree  1070.598967  1072.058527

**Naive Models**

Calculate the mean and median of 'price' on the training and test data and create a column with these values.

Calculate the MAE on the training and test targets between your target and the calculated mean and median.

Calculate the RMSE on the training and test targets between your target and the calculated mean and median.

Insert your metrics into tables result_MAE and result_RMSE with model names 'naive_mean' and 'naive_median'.

In [70]:
mean_price = y_train.mean()
median_price = y_train.median()

In [71]:
y_pred_train_mean = [mean_price] * len(y_train)
y_pred_test_mean = [mean_price] * len(y_test)

In [72]:
y_pred_train_median = [median_price] * len(y_train)
y_pred_test_median = [median_price] * len(y_test)

In [75]:
mae_train_mean = mean_absolute_error(y_train, y_pred_train_mean)
mae_test_mean = mean_absolute_error(y_test, y_pred_test_mean)

mae_train_median = mean_absolute_error(y_train, y_pred_train_median)
mae_test_median = mean_absolute_error(y_test, y_pred_test_median)

In [76]:
rmse_train_mean = root_mean_squared_error(y_train, y_pred_train_mean)
rmse_test_mean = root_mean_squared_error(y_test, y_pred_test_mean)

rmse_train_median = root_mean_squared_error(y_train, y_pred_train_median)
rmse_test_median = root_mean_squared_error(y_test, y_pred_test_median)

In [77]:
result_MAE.loc[2] = ['naive_mean', mae_train_mean, mae_test_mean]
result_RMSE.loc[2] = ['naive_mean', rmse_train_mean, rmse_test_mean]

In [78]:
result_MAE.loc[3] = ['naive_median', mae_train_median, mae_test_median]
result_RMSE.loc[3] = ['naive_median', rmse_train_median, rmse_test_median]

Print your final result_MAE and result_RMSE tables.

In [79]:
result_MAE

               model        train         test
0  linear_regression   781.550473   786.383982
1      decision_tree   753.675997   756.114142
2         naive_mean  1134.361473  1130.888160
3       naive_median  1082.220859  1078.672733

In [80]:
result_RMSE

               model        train         test
0  linear_regression  1115.809281  1354.450530
1      decision_tree  1070.598967  1072.058527
2         naive_mean  1585.609099  1573.238184
3       naive_median  1631.719953  1617.915709

Which is the best model? - decision tree